<a href="https://colab.research.google.com/github/Sharon-Kairu/Linear-Regression-Assignment/blob/main/Linear_Regression_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## In this Linear Regression Assignment, the task is to use the nyc dataset to do 50:50, 80:20, 90:10, 75:25 Training and compare the results. We are also required to calculate the RSME in each.

#Training with 50%

In [3]:
import pandas as pd

In [5]:
nyc=pd.read_csv("/content/ave_hi_nyc_jan_1895-2018.csv", header='infer')
nyc

Date  Value  Anomaly
0    189501   34.2     -3.2
1    189601   34.7     -2.7
2    189701   35.5     -1.9
3    189801   39.6      2.2
4    189901   36.4     -1.0
..      ...    ...      ...
119  201401   35.5     -1.9
120  201501   36.1     -1.3
121  201601   40.8      3.4
122  201701   42.8      5.4
123  201801   38.7      1.3

[124 rows x 3 columns]

In [6]:
nyc.Date=nyc.Date.floordiv(100)
nyc.head()
nyc['Date'].values

array([1895, 1896, 1897, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905,
       1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916,
       1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927,
       1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938,
       1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949,
       1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960,
       1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971,
       1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982,
       1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993,
       1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004,
       2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015,
       2016, 2017, 2018])

In [7]:
from sklearn.model_selection import train_test_split
X = nyc[['Date']].values
y = nyc['Value'].values


X_train, X_test, y_train, y_test = train_test_split( nyc.Date.values.reshape(-1, 1), nyc.Value.values.reshape(-1, 1), test_size=0.5,random_state=104)

In [8]:
from sklearn.linear_model import LinearRegression
linear_regression = LinearRegression()
linear_regression
linear_regression.fit(X_train, y_train)

LinearRegression()

In [9]:
predict = linear_regression.predict(X_test)
predict

array([[38.00955901],
       [38.07789239],
       [38.05254291],
       [37.99963965],
       [38.01176331],
       [38.08891391],
       [38.05584937],
       [38.13189781],
       [38.06136012],
       [38.12638706],
       [38.0845053 ],
       [38.03490849],
       [38.08340315],
       [38.07899455],
       [38.11205909],
       [38.10103757],
       [38.05915582],
       [38.08560745],
       [38.01947837],
       [38.0437257 ],
       [38.04262355],
       [38.03270419],
       [38.09552682],
       [38.07458594],
       [38.06687088],
       [38.00845686],
       [38.10985478],
       [38.11536554],
       [38.02058052],
       [38.04041925],
       [38.05144076],
       [38.13410211],
       [38.10875263],
       [38.00625255],
       [38.0800967 ],
       [38.05364506],
       [38.0393171 ],
       [38.07238164],
       [38.11756984],
       [38.01727407],
       [38.09883327],
       [38.082301  ],
       [38.01837622],
       [38.10434403],
       [38.1230806 ],
       [38

In [10]:
predict=(lambda date: linear_regression.coef_*date+linear_regression.intercept_)(2030)
predict

array([[37.98531168]])

In [11]:
from sklearn.metrics import mean_squared_error
import numpy as np
y_pred = linear_regression.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f'RMSE: {rmse}')

RMSE: 4.857319834776557


Root Mean Squared Error (RMSE) is a metric used to evaluate the accuracy of regression models. It measures the average magnitude of the errors between predicted and actual values, giving you an idea of how well your model's predictions match the true values.A lower RMSE suggests that the model's predictions are closer to the true values, indicating better performance and a more accurate model. Conversely, a higher RMSE indicates greater discrepancies between predicted and actual values


#80:20 Training

In [12]:
X_train, X_test, y_train, y_test = train_test_split( nyc.Date.values.reshape(-1, 1), nyc.Value.values.reshape(-1, 1), test_size=0.2,random_state=104)

In [13]:
linear_regression = LinearRegression()
linear_regression
linear_regression.fit(X_train, y_train)
predict = linear_regression.predict(X_test)
predict

array([[38.37372762],
       [37.81582402],
       [38.02278826],
       [38.45471362],
       [38.35573073],
       [37.72583957],
       [37.99579292],
       [37.37490021],
       [37.9508007 ],
       [37.41989244],
       [37.76183335],
       [38.16676338],
       [37.7708318 ],
       [37.80682558],
       [37.53687222],
       [37.62685668],
       [37.96879759],
       [37.75283491],
       [38.29274161],
       [38.09477582],
       [38.10377427],
       [38.18476027],
       [37.6718489 ],
       [37.84281936],
       [37.90580847]])

In [14]:
predict=(lambda date: linear_regression.coef_*date+linear_regression.intercept_)(2030)
predict

array([[38.57169341]])

In [15]:
y_pred = linear_regression.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f'RMSE: {rmse}')

RMSE: 4.820748640822895


#90:10 Training

In [16]:
X_train, X_test, y_train, y_test = train_test_split( nyc.Date.values.reshape(-1, 1), nyc.Value.values.reshape(-1, 1), test_size=0.1,random_state=104)

In [17]:
linear_regression = LinearRegression()
linear_regression
linear_regression.fit(X_train, y_train)
predict = linear_regression.predict(X_test)
predict

array([[38.03959874],
       [37.60233006],
       [37.76454263],
       [38.10307322],
       [38.0254933 ],
       [37.53180285],
       [37.74338447],
       [37.25674675],
       [37.70812087],
       [37.29201035],
       [37.56001374],
       [37.87738616],
       [37.56706646]])

In [18]:
predict=(lambda date: linear_regression.coef_*date+linear_regression.intercept_)(2030)
predict

array([[38.19475859]])

In [19]:
y_pred = linear_regression.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f'RMSE: {rmse}')

RMSE: 4.698915228958922


#75: 25 Training

In [20]:
X_train, X_test, y_train, y_test = train_test_split( nyc.Date.values.reshape(-1, 1), nyc.Value.values.reshape(-1, 1), test_size=0.25,random_state=104)

In [21]:
linear_regression = LinearRegression()
linear_regression
linear_regression.fit(X_train, y_train)
predict = linear_regression.predict(X_test)
predict

array([[38.40596258],
       [37.97671341],
       [38.135951  ],
       [38.46827294],
       [38.39211583],
       [37.90747967],
       [38.11518088],
       [37.63746809],
       [38.08056401],
       [37.67208496],
       [37.93517316],
       [38.24672498],
       [37.94209654],
       [37.96979003],
       [37.76208882],
       [37.83132256],
       [38.09441076],
       [37.92824979],
       [38.34365222],
       [38.19133799],
       [38.19826137],
       [38.26057173],
       [37.86593942],
       [37.99748353],
       [38.04594714],
       [38.41288595],
       [37.77593557],
       [37.7413187 ],
       [38.33672884],
       [38.21210811],
       [38.14287438]])

In [22]:
predict=(lambda date: linear_regression.coef_*date+linear_regression.intercept_)(2030)
predict

array([[38.5582768]])

In [23]:
y_pred = linear_regression.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f'RMSE: {rmse}')

RMSE: 5.132786094319006
